export const FETCH_NEWS_SUCCESS = "FETCH_NEWS_SUCCESS";
export const SET_FILTER = "SET_FILTER";
export const SET_PERSONALIZED_SOURCES = "SET_PERSONALIZED_SOURCES";
export const FETCH_NEWS_FAILURE = "FETCH_NEWS_FAILURE";
export const SET_LOADER_TRUE = "SET_LOADER_TRUE";
export const SET_LOADER_FALSE = "SET_LOADER_FALSE";
export const CLEAR_ARTICLES = "CLEAR_ARTICLES";
export const CLEAR_PERSONALIZED_SOURCES = "CLEAR_PERSONALIZED_SOURCES";
